---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagbot
spec:
  selector:
    matchLabels:
      app: flagbot
  replicas: 1
  template:
    metadata:
      labels:
        app: flagbot
    spec:
      automountServiceAccountToken: false
      containers:
        - name: flagbot
          image: registry.31337.ooo:5000/flagbot
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: /etc/config/game.k8s.config
            - name: DATABASE_API
              value: http://database-api/
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: game-config
            
